# Configuration for Alacritty, the GPU enhanced terminal emulator.

## Import files (Colors, Fonts, Etc)
import:
  - ~/.config/alacritty/colors.yml
  - ~/.config/alacritty/fonts.yml

# Any items in the `env` entry below will be added as environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #
  # This is done because some libraries to not properly support the term
  # variable "alacritty"
  TERM: xterm-256color

## Terminal window setting
window:
# Uncomment to channel your inner lain
#  title: The Wired
  opacity: 1

## Cursor
cursor:
  style:
    shape: Block
    blinking: Off
  unfocused_hollow: true

## Live config reload
live_config_reload: true

